# DigitalOcean App Platform Configuration
# This file defines how your app is deployed on DigitalOcean

name: secure-redirect-system
region: nyc

# Database Configuration
databases:
  - name: secure-redirect-db
    engine: PG
    version: "16"
    production: true
    cluster_name: secure-redirect-postgres

# Service Configuration
services:
  - name: web
    # Source configuration
    github:
      repo: johnkorey/secure-redirect-system
      branch: master
      deploy_on_push: true

    # Build configuration
    build_command: npm install && npm run build
    
    # Run configuration
    run_command: npm start
    
    # Environment
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month (or basic-xs for $12/month)
    
    # HTTP configuration
    http_port: 3001
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Environment Variables
    envs:
      # Application
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
      
      - key: PORT
        value: "3001"
        scope: RUN_TIME
      
      # JWT Secret - SET THIS IN DIGITALOCEAN DASHBOARD!
      - key: JWT_SECRET
        value: "change-this-to-a-secure-random-string-min-32-characters"
        type: SECRET
        scope: RUN_TIME
      
      # Database (auto-injected by DigitalOcean)
      - key: DATABASE_URL
        value: ${secure-redirect-db.DATABASE_URL}
        scope: RUN_TIME
      
      - key: DB_SSL
        value: "true"
        scope: RUN_TIME
      
      # Optional: IP2Location API
      # Uncomment and set in App Platform dashboard after deployment
      # - key: IP2LOCATION_API_KEY
      #   value: your-key-here
      #   type: SECRET
      #   scope: RUN_TIME
      
      # Optional: Mailgun API
      # - key: MAILGUN_API_KEY
      #   value: your-key-here
      #   type: SECRET
      #   scope: RUN_TIME
      
      # Optional: Telegram Bot
      # - key: TELEGRAM_BOT_TOKEN
      #   value: your-bot-token
      #   type: SECRET
      #   scope: RUN_TIME

    # Routes (custom domain - add after deployment)
    # routes:
    #   - path: /
    #     preserve_path_prefix: true

# Static Site (if you want to serve frontend separately - optional)
# static_sites:
#   - name: frontend
#     github:
#       repo: your-username/your-repo-name
#       branch: main
#       deploy_on_push: true
#     build_command: npm run build
#     output_dir: dist
#     catchall_document: index.html

